import type { CharacterListItem, CharacterSheet } from '../modules/characters/types'

const defaultAbilities = {
  strength: 10,
  dexterity: 10,
  constitution: 10,
  intelligence: 10,
  wisdom: 10,
  charisma: 10,
}

export const stubCharacterSheets: CharacterSheet[] = [
  {
    id: '1',
    name: 'Эларион Сумрачный',
    className: 'Волшебник',
    level: 5,
    species: 'Высший эльф',
    background: 'Мудрец',
    playerName: 'Мария',
    alignment: 'Нейтральный добрый',
    experiencePoints: 6500,
    abilities: {
      strength: 8,
      dexterity: 14,
      constitution: 12,
      intelligence: 18,
      wisdom: 13,
      charisma: 10,
    },
    armorClass: 13,
    initiative: 2,
    speed: 30,
    maxHp: 32,
    currentHp: 28,
    tempHp: 0,
    hitDice: '5d6',
    proficiencyBonus: 3,
    savingThrows: ['Интеллект', 'Мудрость'],
    skills: ['Магия', 'История', 'Анализ', 'Религия', 'Внимательность'],
    personalityTraits: 'Говорит цитатами из древних трактатов.',
    ideals: 'Знание должно служить защите невинных.',
    bonds: 'Ищет пропавшего наставника в Баровии.',
    flaws: 'Не доверяет тем, кто не читал хотя бы десять томов.',
    features: 'Восстановление магии, Ритуальное колдовство, Тайная магия.',
    equipment: 'Посох, компоненты, книга заклинаний, 45 зм.',
    spells: 'Щит, Волшебная стрела, Обнаружение магии, Огненный шар, Туманный шаг.',
    creationType: 'classic',
    campaignId: '1',
    campaignName: 'Проклятие Страда',
    avatarFileName: 'elarion.png',
    antiAchievements: [
      {
        id: 'aa1',
        title: 'Попытался убедить дракона пожертвовать сокровища',
        earnedAt: '28.06.2026',
      },
    ],
  },
  {
    id: '2',
    name: 'Торвин Железный Кулак',
    className: 'Воин',
    level: 3,
    species: 'Дварф',
    background: 'Солдат',
    playerName: 'Игорь',
    alignment: 'Законопослушный нейтральный',
    experiencePoints: 900,
    abilities: {
      strength: 17,
      dexterity: 12,
      constitution: 16,
      intelligence: 10,
      wisdom: 11,
      charisma: 8,
    },
    armorClass: 18,
    initiative: 1,
    speed: 25,
    maxHp: 30,
    currentHp: 30,
    tempHp: 0,
    hitDice: '3d10',
    proficiencyBonus: 2,
    savingThrows: ['Сила', 'Телосложение'],
    skills: ['Атлетика', 'Запугивание', 'Внимательность'],
    personalityTraits: 'Молчалив, но надёжен в бою.',
    ideals: 'Честь отряда важнее личной выгоды.',
    bonds: 'Долг таверне «Красный Дракон» за приют.',
    flaws: 'Слишком прямолинеен в переговорах.',
    features: 'Боевой стиль: Защита, Второе дыхание, Всплеск действий.',
    equipment: 'Кольчуга, щит, боевой топор, 20 зм.',
    spells: '',
    creationType: 'campaign',
    campaignId: '2',
    campaignName: 'Таверна у Красного Дракона',
    avatarFileName: 'torvin.png',
    questionnaireAnswers: {
      tavern: 'Постоянный гость',
      faction: 'Городская стража',
      goal: 'Защищать таверну от бандитов и заработать на новый доспех.',
    },
    antiAchievements: [
      {
        id: 'aa2',
        title: 'Критически провалил проверку Скрытности в таверне',
        earnedAt: '15.06.2026',
      },
    ],
  },
  {
    id: '4',
    name: 'Сестра Мира',
    className: 'Жрец',
    level: 4,
    species: 'Человек',
    background: 'Аколит',
    playerName: 'Елена',
    alignment: 'Законопослушный добрый',
    experiencePoints: 2700,
    abilities: {
      strength: 10,
      dexterity: 10,
      constitution: 14,
      intelligence: 12,
      wisdom: 17,
      charisma: 13,
    },
    armorClass: 16,
    initiative: 0,
    speed: 30,
    maxHp: 28,
    currentHp: 28,
    tempHp: 0,
    hitDice: '4d8',
    proficiencyBonus: 2,
    savingThrows: ['Мудрость', 'Харизма'],
    skills: ['Медицина', 'Религия', 'Проницательность'],
    personalityTraits: 'Утешает напуганных и никогда не повышает голос.',
    ideals: 'Свет должен прогонять тьму.',
    bonds: 'Храм в Баровии — единственное место покоя.',
    flaws: 'Слишком доверчива к «потерянным душам».',
    features: 'Божественный канал, Наставление',
    equipment: 'Кольчуга, щит, символ веры',
    spells: 'Лечение ран, Направляющий луч',
    creationType: 'campaign',
    campaignId: '1',
    campaignName: 'Проклятие Страда',
    avatarFileName: 'mira.png',
    antiAchievements: [
      {
        id: 'aa3',
        title: 'Забыл, зачем пришли в подземелье',
        earnedAt: '14.06.2026',
      },
    ],
  },
  {
    id: '5',
    name: 'Грим Костолом',
    className: 'Варвар',
    level: 4,
    species: 'Орк',
    background: 'Отшельник',
    playerName: 'Дмитрий',
    alignment: 'Хаотичный нейтральный',
    experiencePoints: 2700,
    abilities: {
      strength: 18,
      dexterity: 12,
      constitution: 16,
      intelligence: 8,
      wisdom: 10,
      charisma: 9,
    },
    armorClass: 15,
    initiative: 1,
    speed: 35,
    maxHp: 38,
    currentHp: 32,
    tempHp: 0,
    hitDice: '4d12',
    proficiencyBonus: 2,
    savingThrows: ['Сила', 'Телосложение'],
    skills: ['Атлетика', 'Запугивание', 'Выживание'],
    personalityTraits: 'Решает проблемы топором, если не знает другого способа.',
    ideals: 'Сила — единственная честная валюта.',
    bonds: 'Клятва защищать слабых в отряде.',
    flaws: 'Не понимает метафор.',
    features: 'Ярость, Безрассудная атака',
    equipment: 'Секира, шкуры, 10 зм.',
    spells: '',
    creationType: 'campaign',
    campaignId: '1',
    campaignName: 'Проклятие Страда',
    avatarFileName: 'grimm.png',
    antiAchievements: [],
  },
  {
    id: '3',
    name: 'Лира Мягкий Шаг',
    className: 'Плут',
    level: 1,
    species: 'Полурослик',
    background: '—',
    playerName: 'Анна',
    alignment: 'Хаотичный добрый',
    experiencePoints: 0,
    abilities: { ...defaultAbilities, dexterity: 16, charisma: 14 },
    armorClass: 12,
    initiative: 3,
    speed: 25,
    maxHp: 9,
    currentHp: 9,
    tempHp: 0,
    hitDice: '1d8',
    proficiencyBonus: 2,
    savingThrows: [],
    skills: ['Скрытность', 'Ловкость рук'],
    personalityTraits: '',
    ideals: '',
    bonds: '',
    flaws: '',
    features: '',
    equipment: '',
    spells: '',
    creationType: 'general',
    questionnaireAnswers: {
      name: 'Лира Мягкий Шаг',
      background: 'Полурослик из приграничья, любит истории и пироги.',
      experience: 'Играл 1–3 раза',
      role: 'Социальный',
      boundaries: 'Без насилия над детьми|Без насилия над животными',
      notes: 'Хочу быть дипломатом в группе',
      className: 'Плут',
      level: '1',
      species: 'Полурослик',
      playerName: 'Анна',
      alignment: 'Хаотичный добрый',
      experiencePoints: '0',
      proficiencyBonus: '+2',
      strength: '10',
      dexterity: '16',
      constitution: '10',
      intelligence: '10',
      wisdom: '10',
      charisma: '14',
      armorClass: '12',
      initiative: '+3',
      speed: '25',
      hitDice: '1d8',
      maxHp: '9',
      currentHp: '9',
      tempHp: '0',
      skills: 'Скрытность|Ловкость рук',
    },
  },
]

export const stubCharacterList: CharacterListItem[] = stubCharacterSheets.map((s) => ({
  id: s.id,
  name: s.name,
  className: s.className,
  level: s.level,
  species: s.species,
  campaignName: s.campaignName,
  creationType: s.creationType,
  updatedAt: '2026-07-04',
}))
