import type { CharacterSheet } from './types'

const defaultAbilities = {
  strength: 10,
  dexterity: 10,
  constitution: 10,
  intelligence: 10,
  wisdom: 10,
  charisma: 10,
}

export const emptyCharacterSheet = (): CharacterSheet => ({
  id: '',
  name: '',
  className: '',
  level: 1,
  species: '',
  background: '',
  playerName: '',
  alignment: '',
  experiencePoints: 0,
  abilities: { ...defaultAbilities },
  armorClass: 10,
  initiative: 0,
  speed: 30,
  maxHp: 8,
  currentHp: 8,
  tempHp: 0,
  hitDice: '1d8',
  proficiencyBonus: 2,
  savingThrows: [],
  skills: [],
  personalityTraits: '',
  ideals: '',
  bonds: '',
  flaws: '',
  features: '',
  equipment: '',
  spells: '',
  creationType: 'classic',
})
