import type { CampaignFormField } from './types'
import {
  DND_ALIGNMENTS,
  DND_ARMOR_CLASS,
  DND_BONDS,
  DND_CLASSES,
  DND_EQUIPMENT,
  DND_FEATURES,
  DND_FLAWS,
  DND_HIT_DICE,
  DND_HP,
  DND_IDEALS,
  DND_INITIATIVE,
  DND_LEVELS,
  DND_PERSONALITY_TRAITS,
  DND_PROFICIENCY_BONUSES,
  DND_SAVING_THROWS,
  DND_SKILLS,
  DND_SPEED,
  DND_SPELLS,
  DND_SPECIES,
  DND_XP,
  DND_ABILITY_SCORES,
} from './sheetOptions'

/** Каталог полей листа D&D 2024 — база для общей и кампанийной анкеты. */
export const SHEET_FIELD_CATALOG: CampaignFormField[] = [
  {
    id: 'avatar',
    label: 'Аватар',
    type: 'file',
    section: 'Персонаж',
  },
  {
    id: 'name',
    label: 'Имя персонажа',
    type: 'text',
    placeholder: 'Как зовут вашего героя?',
    section: 'Основная информация',
  },
  {
    id: 'background',
    label: 'Предыстория',
    type: 'textarea',
    placeholder: 'Происхождение, мотивация, история персонажа...',
    section: 'Основная информация',
  },
  {
    id: 'className',
    label: 'Класс',
    type: 'select',
    options: [...DND_CLASSES],
    section: 'Основная информация',
  },
  {
    id: 'level',
    label: 'Уровень',
    type: 'select',
    options: DND_LEVELS,
    section: 'Основная информация',
  },
  {
    id: 'species',
    label: 'Вид (Species)',
    type: 'select',
    options: [...DND_SPECIES],
    section: 'Основная информация',
  },
  {
    id: 'playerName',
    label: 'Имя игрока',
    type: 'select',
    options: ['—', 'Мария', 'Игорь', 'Анна', 'Дмитрий', 'Елена'],
    section: 'Основная информация',
  },
  {
    id: 'alignment',
    label: 'Мировоззрение',
    type: 'select',
    options: [...DND_ALIGNMENTS],
    section: 'Основная информация',
  },
  {
    id: 'experiencePoints',
    label: 'Опыт (XP)',
    type: 'select',
    options: DND_XP,
    section: 'Основная информация',
  },
  {
    id: 'proficiencyBonus',
    label: 'Бонус мастерства',
    type: 'select',
    options: DND_PROFICIENCY_BONUSES,
    section: 'Основная информация',
  },
  {
    id: 'strength',
    label: 'Сила (STR)',
    type: 'select',
    options: DND_ABILITY_SCORES,
    section: 'Характеристики',
  },
  {
    id: 'dexterity',
    label: 'Ловкость (DEX)',
    type: 'select',
    options: DND_ABILITY_SCORES,
    section: 'Характеристики',
  },
  {
    id: 'constitution',
    label: 'Телосложение (CON)',
    type: 'select',
    options: DND_ABILITY_SCORES,
    section: 'Характеристики',
  },
  {
    id: 'intelligence',
    label: 'Интеллект (INT)',
    type: 'select',
    options: DND_ABILITY_SCORES,
    section: 'Характеристики',
  },
  {
    id: 'wisdom',
    label: 'Мудрость (WIS)',
    type: 'select',
    options: DND_ABILITY_SCORES,
    section: 'Характеристики',
  },
  {
    id: 'charisma',
    label: 'Харизма (CHA)',
    type: 'select',
    options: DND_ABILITY_SCORES,
    section: 'Характеристики',
  },
  {
    id: 'armorClass',
    label: 'Класс брони (КБ)',
    type: 'select',
    options: DND_ARMOR_CLASS,
    section: 'Бой',
  },
  {
    id: 'initiative',
    label: 'Инициатива',
    type: 'select',
    options: DND_INITIATIVE,
    section: 'Бой',
  },
  {
    id: 'speed',
    label: 'Скорость',
    type: 'select',
    options: DND_SPEED,
    section: 'Бой',
  },
  {
    id: 'hitDice',
    label: 'Кости хитов',
    type: 'select',
    options: DND_HIT_DICE,
    section: 'Бой',
  },
  {
    id: 'maxHp',
    label: 'Макс. ХП',
    type: 'select',
    options: DND_HP,
    section: 'Бой',
  },
  {
    id: 'currentHp',
    label: 'Текущие ХП',
    type: 'select',
    options: DND_HP,
    section: 'Бой',
  },
  {
    id: 'tempHp',
    label: 'Временные ХП',
    type: 'select',
    options: ['0', '5', '10', '15', '20', '25', '30'],
    section: 'Бой',
  },
  {
    id: 'savingThrows',
    label: 'Владение спасбросками',
    type: 'multiselect',
    options: [...DND_SAVING_THROWS],
    section: 'Спасброски и навыки',
  },
  {
    id: 'skills',
    label: 'Владение навыками',
    type: 'multiselect',
    options: [...DND_SKILLS],
    section: 'Спасброски и навыки',
  },
  {
    id: 'personalityTraits',
    label: 'Черты характера',
    type: 'select',
    options: DND_PERSONALITY_TRAITS,
    section: 'Личность',
  },
  {
    id: 'ideals',
    label: 'Идеалы',
    type: 'select',
    options: DND_IDEALS,
    section: 'Личность',
  },
  {
    id: 'bonds',
    label: 'Привязанности',
    type: 'select',
    options: DND_BONDS,
    section: 'Личность',
  },
  {
    id: 'flaws',
    label: 'Слабости',
    type: 'select',
    options: DND_FLAWS,
    section: 'Личность',
  },
  {
    id: 'features',
    label: 'Особенности и черты',
    type: 'select',
    options: DND_FEATURES,
    section: 'Особенности и снаряжение',
  },
  {
    id: 'equipment',
    label: 'Снаряжение',
    type: 'select',
    options: DND_EQUIPMENT,
    section: 'Особенности и снаряжение',
  },
  {
    id: 'spells',
    label: 'Заклинания',
    type: 'select',
    options: DND_SPELLS,
    section: 'Особенности и снаряжение',
  },
]

export function getSheetFieldById(id: string): CampaignFormField | undefined {
  return SHEET_FIELD_CATALOG.find((field) => field.id === id)
}
